---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '15 3 * * 1'
permissions:
  contents: read
jobs:
  php-lint:
    name: PHP linter
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Show the Composer version
        run: ./Build/Scripts/runTests.sh -s composer -- --version
      - name: Show the Composer configuration
        run: ./Build/Scripts/runTests.sh -s composer config --global --list
      - name: Cache dependencies installed with composer
        uses: actions/cache@v5
        with:
          key: "php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-\n"
      - name: Install composer dependencies
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -t ${{matrix.typo3-version}} -s composerUpdate${{matrix.composer-dependencies}}
      - name: Lint PHP
        run: |
          Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s lintPhp
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: "11.5"
            php-version: "7.4"
            composer-dependencies: Max
          - typo3-version: "11.5"
            php-version: "8.0"
            composer-dependencies: Max
          - typo3-version: "11.5"
            php-version: "8.1"
            composer-dependencies: Max
          - typo3-version: "11.5"
            php-version: "8.2"
            composer-dependencies: Max
          - typo3-version: "11.5"
            php-version: "8.3"
            composer-dependencies: Max
          - typo3-version: "11.5"
            php-version: "8.4"
            composer-dependencies: Max
  code-quality:
    name: Code quality checks
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          tools: composer:v2
          extensions: zip
          coverage: none
      - name: Show the Composer version
        run: ./Build/Scripts/runTests.sh -s composer -- --version
      - name: Show the Composer configuration
        run: ./Build/Scripts/runTests.sh -s composer config --global --list
      - name: Cache dependencies installed with composer
        uses: actions/cache@v5
        with:
          key: "php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-\n"
      - name: Install composer dependencies
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -t ${{matrix.typo3-version}} -s composerUpdate${{matrix.composer-dependencies}}
      - name: Run code quality checks
        run: |
          Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s composer check:${{ matrix.command }}
    strategy:
      fail-fast: false
      matrix:
        command:
          - "composer:normalize"
          - "php:cs-fixer"
          - "php:rector"
          - "php:sniff"
          - "php:stan"
          - "typoscript:lint"
          - "xliff:lint"
        # For consistency, the PHP version should match the default PHP version in `runTests.sh`.
        php-version:
          - "8.2"
        # For consistency, the TYPO3 version should match the default TYPO3 version in `runTests.sh`.
        typo3-version:
          - "11.5"
        composer-dependencies:
          - Max
  prepare-release:
    name: Check prepare release script
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run prepare release
        run: Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s composer prepare-release
    strategy:
      matrix:
        php-version:
          - "8.2"
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    needs: php-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Show the Composer version
        run: ./Build/Scripts/runTests.sh -s composer -- --version
      - name: Show the Composer configuration
        run: ./Build/Scripts/runTests.sh -s composer config --global --list
      - name: Cache dependencies installed with composer
        uses: actions/cache@v5
        with:
          key: "php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-\n"
      - name: Install composer dependencies
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -t ${{matrix.typo3-version}} -s composerUpdate${{matrix.composer-dependencies}}
      - name: Run unit tests
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s unit
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: "11.5"
            php-version: "7.4"
            composer-dependencies: Min
          - typo3-version: "11.5"
            php-version: "7.4"
            composer-dependencies: Max
          - typo3-version: "11.5"
            php-version: "8.3"
            composer-dependencies: Min
          - typo3-version: "11.5"
            php-version: "8.3"
            composer-dependencies: Max
  functional-tests:
    name: Functional tests
    runs-on: ubuntu-24.04
    timeout-minutes: 6
    needs: php-lint
    env:
      DB_DATABASE: typo3
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Show the Composer version
        run: ./Build/Scripts/runTests.sh -s composer -- --version
      - name: Show the Composer configuration
        run: ./Build/Scripts/runTests.sh -s composer config --global --list
      - name: Cache dependencies installed with composer
        uses: actions/cache@v5
        with:
          key: "php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php-${{ matrix.php-version }}-typo3-${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-\n"
      - name: Install composer dependencies
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -t ${{matrix.typo3-version}} -s composerUpdate${{matrix.composer-dependencies}}
      - name: Run functional tests
        run: |
          ./Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -d ${{ matrix.dbms }} -s functional
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: "11.5"
            php-version: "7.4"
            dbms: "mysql"
            composer-dependencies: Min
          - typo3-version: "11.5"
            php-version: "7.4"
            dbms: "mysql"
            composer-dependencies: Max
          - typo3-version: "11.5"
            php-version: "8.3"
            dbms: "mysql"
            composer-dependencies: Min
          - typo3-version: "11.5"
            php-version: "8.3"
            dbms: "mysql"
            composer-dependencies: Max
  legacy-functional-tests:
    name: Legacy functional tests
    runs-on: ubuntu-24.04
    timeout-minutes: 7
    needs: php-lint
    env:
      DB_DATABASE: typo3
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          php-version: "${{ matrix.php-version }}"
          ini-file: development
          tools: composer:v2
          extensions: dom, json, libxml, mysqli, zip
          coverage: none
          ini-values: error_reporting=E_ALL
      - name: Show Composer version
        run: composer --version
      - name: Show the Composer configuration
        run: composer config --global --list
      - name: Cache dependencies installed with composer
        uses: actions/cache@v5
        with:
          key: "php${{ matrix.php-version }}-typo3${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-typo3${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-\n"
      - name: Install TYPO3 Core
        env:
          TYPO3: "${{ matrix.typo3-version }}"
        run: |
          composer require --no-ansi --no-interaction --no-progress --no-install typo3/cms-core:"$TYPO3"
          composer show
      - name: Install lowest dependencies with composer
        if: "matrix.composer-dependencies == 'lowest'"
        run: |
          composer update --no-ansi --no-interaction --no-progress --with-dependencies --prefer-lowest
          composer show
      - name: Install highest dependencies with composer
        if: "matrix.composer-dependencies == 'highest'"
        run: |
          composer update --no-ansi --no-interaction --no-progress --with-dependencies
          composer show
      - name: Start MySQL
        run: "sudo /etc/init.d/mysql start"
      - name: Create the tests directory
        run: "mkdir -p .Build/public/typo3temp/var/tests"
      - name: Run legacy functional tests
        run: |
          export typo3DatabaseName="$DB_DATABASE";
          export typo3DatabaseHost="$DB_HOST";
          export typo3DatabaseUsername="$DB_USER";
          export typo3DatabasePassword="$DB_PASSWORD";
          composer check:tests:legacy-functional
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: "^11.5"
            php-version: "7.4"
            composer-dependencies: lowest
          - typo3-version: "^11.5"
            php-version: "7.4"
            composer-dependencies: highest
          - typo3-version: "^11.5"
            php-version: "8.3"
            composer-dependencies: lowest
          - typo3-version: "^11.5"
            php-version: "8.3"
            composer-dependencies: highest
  shellcheck:
    name: Check shell scripts
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check scripts
        run: |
          Build/Scripts/runTests.sh -s shellcheck
  documentation:
    name: Documentation
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test if the documentation will render without warnings
        run: |
          Build/Scripts/runTests.sh -s docsGenerate
